### ISSUE TITLE
Large URLs

### ISSUE THREAD

**Issue by jtaylorjfd** [sjelfull/craft3-shortcut#11]
### Describe the bug

The max URL field length is 400 characters is there a way to change this without manually going into the database and altering it.

### Steps to reproduce

1. Attempt to use on a URL which as more than 400 characters
2. Will result in an database error

### Craft CMS version

4.8.0

### Plugin version

4.0.0

**Comment by engram-design** [comment]
Updated in [4.0.1](https://github.com/verbb/shortcut/releases/tag/4.0.1)

**Comment by gglnx** [comment]
@engram-design The migration is broken. The change for `elementType` is wrong: https://github.com/verbb/shortcut/commit/7db6963b16e1d4131757bd06ea9889285da08869#diff-eeaee5832c4b09244e3b5fcf333015ab6c248646e1a72e528c6bc11b2a6174c2R16

**Comment by engram-design** [comment]
My mistake, should be fixed in [4.0.2](https://github.com/verbb/shortcut/releases/tag/4.0.2)
