### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by worshiplive** [sjelfull/craft3-shortcut#3]
Using the exact url example this is returned.

Return value of superbig\shortcut\services\ShortcutService::getByUrl() must be an instance of superbig\shortcut\models\ShortcutModel, null returned

**Comment by JMKelley** [comment]
I also get this.

**Comment by worshiplive** [comment]
I upgraded to the newest Freeform to 2.0.4 and that cleared up the install issue.

**Comment by sjelfull** [comment]
This should be fixed with the latest release. There was a couple problems when creating shortcuts for url's.
