### ISSUE TITLE
Cannot Install

### ISSUE THREAD

**Issue by worshiplive** [sjelfull/craft3-shortcut#4]
Tried to install via Plugin Store and got this in the info dump...

  Problem 1
    - Conclusion: remove hashids/hashids 1.0.6
    - Conclusion: remove solspace/craft3-freeform 2.0.1
    - Conclusion: don't install hashids/hashids 1.0.6
    - Conclusion: don't install hashids/hashids 2.0.4
    - Conclusion: don't install hashids/hashids 1.0.5
    - Conclusion: don't install hashids/hashids 2.0.3
    - Conclusion: don't install hashids/hashids 1.0.4
    - Conclusion: don't install hashids/hashids 2.0.2
    - Conclusion: don't install hashids/hashids 1.0.3
    - Installation request for solspace/craft3-freeform 2.0.1 -> satisfiable by solspace/craft3-freeform[2.0.1].
    - Installation request for superbig/craft3-shortcut 2.0.0 -> satisfiable by superbig/craft3-shortcut[2.0.0].
    - solspace/craft3-freeform 2.0.1 requires hashids/hashids ^1.0 -> satisfiable by hashids/hashids[1.0.6, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5].
    - Can only install one of: hashids/hashids[2.0.0, 1.0.0].
    - Can only install one of: hashids/hashids[2.0.0, 1.0.1].
    - Can only install one of: hashids/hashids[2.0.0, 1.0.2].
    - superbig/craft3-shortcut 2.0.0 requires hashids/hashids ^2.0 -> satisfiable by hashids/hashids[2.0.1, 2.0.0, 2.0.4, 2.0.3, 2.0.2].
    - Conclusion: don't install hashids/hashids 2.0.1

**Comment by sjelfull** [comment]
Thanks for the report. Freeform is constrained to a pretty old version of hashids. Solspace has confirmed that they will upgrade it soon.

**Comment by worshiplive** [comment]
Sounds good! Thanks for taking a look.

**Comment by sjelfull** [comment]
Have removed this dependency now.
