### ISSUE TITLE
DB Export Error

### ISSUE THREAD

**Issue by jacobgraf** [sjelfull/craft3-shortcut#5]
Trying to export a MySQL file from local dev so I can load it onto staging and when I export it from Querious, I get the following error...

`Specified key was too long; max key length is 767 bytes`

`CREATE TABLE `shortcut_shortcuts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `dateCreated` datetime NOT NULL,
  `dateUpdated` datetime NOT NULL,
  `uid` char(36) NOT NULL DEFAULT '0',
  `siteId` int(11) NOT NULL,
  `elementId` int(11) DEFAULT NULL,
  `elementType` varchar(255) DEFAULT NULL,
  `code` varchar(255) NOT NULL DEFAULT '',
  `url` varchar(400) NOT NULL DEFAULT '',
  `urlHash` varchar(400) NOT NULL DEFAULT '',
  `hits` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `shortcut_shortcuts_code_unq_idx` (`code`),
  UNIQUE KEY `shortcut_shortcuts_urlHash_unq_idx` (`urlHash`),
  KEY `shortcut_shortcuts_siteId_fk` (`siteId`),
  KEY `shortcut_shortcuts_elementId_fk` (`elementId`),
  CONSTRAINT `shortcut_shortcuts_elementId_fk` FOREIGN KEY (`elementId`) REFERENCES `elements` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `shortcut_shortcuts_siteId_fk` FOREIGN KEY (`siteId`) REFERENCES `sites` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8`

**Comment by sjelfull** [comment]
What MySQL versions are you running locally and in staging? This might be relevant: https://stackoverflow.com/questions/1814532/1071-specified-key-was-too-long-max-key-length-is-767-bytes

**Comment by jacobgraf** [comment]
**Local:** MySQL 5.7.25
**Staging:** MariaDB 10.1.38

**Comment by sjelfull** [comment]
This seems to be related to the database: https://stackoverflow.com/questions/42043205/how-to-fix-mysql-index-column-size-too-large-laravel-migrate/52778785#52778785

Don't think there is anything I can do here.
