### ISSUE TITLE
Shortcut returning NULL on first page load

### ISSUE THREAD

**Issue by jacobgraf** [sjelfull/craft3-shortcut#6]
The first time I load a page with a shortcut on it, it renders NULL in the browser. If I refresh, it goes away and the shortcut link appears just fine, but I am trying to figure out how to fix it so it doesn't show NULL on first load? Here is my template code. Thanks!

```
{% set shortcut = craft.shortcut.get({ element: event }) %}
<p class="m-0 mb-2 text-sm"><a href="{{ event.url }}">{{ shortcut.getUrl() }}</a></p>
```

**Comment by jpcarpenter** [comment]
+1 - Having this same issue while attempting to create short url's from within Element API.

**Comment by jpcarpenter** [comment]
@jacobgraf I did a little digging, and on line 293 in ShortcutService.php there is a `var_dump(code)` that is causing the issue for me. Once commented out, everything seems to be functioning normally.

**Comment by frontedbe** [comment]
A release fixing this would be cool!

**Comment by sjelfull** [comment]
Thanks for reporting, tagged a release with fix just now.
