### ISSUE TITLE
FR: Shorter URLs?

### ISSUE THREAD

**Issue by gglnx** [sjelfull/craft3-shortcut#7]
Would it be possible to add an option (`shortcut.php`) or a constant to adjust the length of hashes (see https://github.com/sjelfull/craft3-shortcut/blob/master/src/services/ShortcutService.php#L290)?

**Comment by sjelfull** [comment]
I'll consider adding it at some point. Always open to PRs!

**Comment by engram-design** [comment]
Added in [3.0.1](https://github.com/verbb/shortcut/releases/tag/3.0.1)
