### ISSUE TITLE
Integrity constraint violation

### ISSUE THREAD

**Issue by gglnx** [sjelfull/craft3-shortcut#8]
If you soft-delete an entry for example with URL "http://craftcms.test/news/my-news" and afterwards create a new entry with the same URL, `Shortcut::$plugin->shortcutService->get()` throws an 'Integrity constraint violation' exception.

> SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'fb33c2ce743601ba312a7a050af289df' for key 'shortcut_shortcuts_urlHash_unq_idx'
> 
> The SQL being executed was: INSERT INTO `shortcut_shortcuts` (`url`, `urlHash`, `code`, `siteId`, `hits`, `elementId`, `elementType`, `dateCreated`, `dateUpdated`, `uid`) VALUES ('http://craftcms.test/news/my-news', '49dd41058d30f4efb9d45dd01bdb6210', '', 1, 0, 71163, 'craft\\elements\\Entry', '2020-07-09 14:37:17', '2020-07-09 14:37:17', 'b586676e-11a9-4443-88cb-ccddfcd68fb0')

**Comment by engram-design** [comment]
Fixed in [3.0.1](https://github.com/verbb/shortcut/releases/tag/3.0.1)
